services:
  # MARK: DEV
  app-dev:
    container_name: app-dev
    profiles: ["dev"]
    build:
      context: ./backend
      args:
        ENV: dev
    env_file: "./backend/.env.dev"
    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - 8000:8000
    volumes:
      - ./backend/app/:/app/app/
    networks:
      - dev

networks:
  dev: